name: NewChunkNotifier
main: com.pandemoneus.newChunkNotifier.NewChunkNotifier
version: 1.01
author: 'Pandemoneus'

commands:
    newchunknotifier:
        description: NewChunkNotifier
        usage: |
               /<command>
    ncn:
        description: NewChunkNotifier
        usage: |
               /<command>